### ISSUE TITLE
generator-ui5 errors

### ISSUE THREAD

**Issue by vibubnin** [bkrrr/generator-ui5#10]
Hello bkrrr, I liked your idea of ​​developing generator-ui5, but because of the errors that occurred, it was not possible to install several templates: masterPage, ui5: spage, ui5: vc. An empty ui5: fragment is installed, but for some reason the xml-fragment has the extension .js and when you install a fragment with the dialog, an empty fragment is also installed. Could you tell me why errors get out? What version of node.js and npm do you use?

**Comment by bkrrr** [comment]
Hi vibubnin,

as described in the readme all sub generators are flagged as under
development, same holds for the masterDetail template.
Just merge the relevant files in a WebIDE template and you can start
working.


   - you can
   -



   - I realized that gulp/grunt isn't working quite well for this kind of
   projects
   - I made some stupid decisions(aka instead if using the WebIDE  files -
   i  made my own config)

I use the files almost everyday for work. But i will not further develop
this. Its way too much work one person and the next step would be to get
rid of grunt in favor of node.js scripts .... what would be even more work.


If you want to contribute - feel free to do so; i will merge it, if it is
somewhat clean code.



regards, Benedikt
